repos:
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        files: ^file-organiser-python/(src|tests)/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: bash -c 'cd file-organiser-go && gofmt -w .'
        language: system
        pass_filenames: false

      - id: go-vet
        name: go vet
        entry: bash -c 'cd file-organiser-go && go vet ./...'
        language: system
        pass_filenames: false
